export const CONCEPTS = [
  // PHYSICS
  {
    id: "jee-concept-newtons-laws",
    subjectId: "Physics",
    chapterId: "phy-mechanics",
    label: "Newton's Laws of Motion",
    summary: "The fundamental laws governing the motion of bodies under the action of forces. Crucial for solving mechanics problems.",
    importance: "high",
    category: "Mechanics",
    formula: "F = ma",
    complexity: "O(1)",
    commonTraps: ["Forgetting pseudo forces in non-inertial frames", "Incorrect free body diagrams"],
  },
  {
    id: "jee-concept-work-energy",
    subjectId: "Physics",
    chapterId: "phy-mechanics",
    label: "Work-Energy Theorem",
    summary: "The net work done on an object by all forces equals the change in its kinetic energy.",
    importance: "high",
    category: "Mechanics",
    formula: "W_{net} = \\Delta K",
    commonTraps: ["Not accounting for work done by non-conservative forces like friction"],
  },
  {
    id: "jee-concept-coulombs-law",
    subjectId: "Physics",
    chapterId: "phy-electro",
    label: "Coulomb's Law",
    summary: "Quantifies the amount of force between two stationary, electrically charged particles.",
    importance: "high",
    category: "Electromagnetism",
    formula: "F = k \\frac{|q_1 q_2|}{r^2}",
    commonTraps: ["Ignoring the vector nature of electric force in 2D/3D problems"],
  },
  {
    id: "jee-concept-gauss-law",
    subjectId: "Physics",
    chapterId: "phy-electro",
    label: "Gauss's Law",
    summary: "Relates the distribution of electric charge to the resulting electric field.",
    importance: "high",
    category: "Electromagnetism",
    formula: "\\oint \\mathbf{E} \\cdot d\\mathbf{A} = \\frac{Q_{enc}}{\\varepsilon_0}",
    commonTraps: ["Applying Gauss's law when the charge distribution lacks symmetry"],
  },
  {
    id: "jee-concept-photoelectric",
    subjectId: "Physics",
    chapterId: "phy-optics",
    label: "Photoelectric Effect",
    summary: "Emission of electrons when electromagnetic radiation, such as light, hits a material.",
    importance: "medium",
    category: "Modern Physics",
    formula: "K_{max} = h\\nu - \\Phi",
    commonTraps: ["Confusing stopping potential with kinetic energy units (eV vs Joules)"],
  },
  {
    id: "jee-concept-thermodynamics-first-law",
    subjectId: "Physics",
    chapterId: "phy-thermo",
    label: "First Law of Thermodynamics",
    summary: "Energy conservation principle applied to thermodynamic systems.",
    importance: "high",
    category: "Thermodynamics",
    formula: "\\Delta Q = \\Delta U + \\Delta W",
    commonTraps: ["Sign conventions for work done BY the gas vs ON the gas"],
  },

  // CHEMISTRY
  {
    id: "jee-concept-ideal-gas",
    subjectId: "Chemistry",
    chapterId: "chem-physical",
    label: "Ideal Gas Equation",
    summary: "Equation of state of a hypothetical ideal gas.",
    importance: "high",
    category: "Physical Chemistry",
    formula: "PV = nRT",
    commonTraps: ["Using incorrect units for R depending on pressure units (atm vs Pa)"],
  },
  {
    id: "jee-concept-nernst-equation",
    subjectId: "Chemistry",
    chapterId: "chem-physical",
    label: "Nernst Equation",
    summary: "Relates the reduction potential of an electrochemical reaction to standard electrode potential and activities.",
    importance: "high",
    category: "Physical Chemistry",
    formula: "E = E^\\circ - \\frac{RT}{nF} \\ln Q",
    commonTraps: ["Forgetting to balance electrons (n) in the overall cell reaction"],
  },
  {
    id: "jee-concept-hyperconjugation",
    subjectId: "Chemistry",
    chapterId: "chem-organic",
    label: "Hyperconjugation",
    summary: "Stabilizing interaction that results from the interaction of the electrons in a sigma bond with an adjacent empty or partially filled p-orbital.",
    importance: "medium",
    category: "Organic Chemistry",
    commonTraps: ["Confusing hyperconjugation with resonance or inductive effects"],
  },
  {
    id: "jee-concept-sn1-sn2",
    subjectId: "Chemistry",
    chapterId: "chem-organic",
    label: "Nucleophilic Substitution (SN1 & SN2)",
    summary: "Key reaction mechanisms in organic chemistry where a nucleophile displaces a leaving group.",
    importance: "high",
    category: "Organic Chemistry",
    commonTraps: ["Ignoring stereochemistry (inversion in SN2, racemization in SN1)", "Wrong solvent choice predictions"],
  },
  {
    id: "jee-concept-coordination-cft",
    subjectId: "Chemistry",
    chapterId: "chem-inorganic",
    label: "Crystal Field Theory (CFT)",
    summary: "Describes the breaking of degeneracies of electron orbital states due to a static electric field produced by surrounding point charges (ligands).",
    importance: "high",
    category: "Inorganic Chemistry",
    formula: "\\Delta_o = \\text{Crystal Field Splitting Energy}",
    commonTraps: ["Incorrectly pairing electrons before filling all t2g/eg orbitals in weak field ligands"],
  },

  // MATHEMATICS
  {
    id: "jee-concept-lhopital-rule",
    subjectId: "Mathematics",
    chapterId: "math-calculus",
    label: "L'Hôpital's Rule",
    summary: "A method to evaluate indeterminate forms of limits.",
    importance: "high",
    category: "Calculus",
    formula: "\\lim_{x \\to c} \\frac{f(x)}{g(x)} = \\lim_{x \\to c} \\frac{f'(x)}{g'(x)}",
    commonTraps: ["Applying the rule when the limit is NOT in an indeterminate form (0/0 or \\infty/\\infty)"],
  },
  {
    id: "jee-concept-integration-parts",
    subjectId: "Mathematics",
    chapterId: "math-calculus",
    label: "Integration by Parts",
    summary: "Transforms the integral of a product of functions into a different, hopefully simpler, integral.",
    importance: "high",
    category: "Calculus",
    formula: "\\int u \\, dv = uv - \\int v \\, du",
    commonTraps: ["Choosing the wrong function for 'u' (Remember ILATE rule!)"],
  },
  {
    id: "jee-concept-matrix-adj",
    subjectId: "Mathematics",
    chapterId: "math-algebra",
    label: "Adjoint of a Matrix",
    summary: "The transpose of the cofactor matrix.",
    importance: "medium",
    category: "Algebra",
    formula: "A \\cdot \\text{adj}(A) = |A| I",
    commonTraps: ["Forgetting that |adj(A)| = |A|^{n-1}"],
  },
  {
    id: "jee-concept-binomial-theorem",
    subjectId: "Mathematics",
    chapterId: "math-algebra",
    label: "Binomial Theorem",
    summary: "Algebraic expansion of powers of a binomial.",
    importance: "high",
    category: "Algebra",
    formula: "(x+y)^n = \\sum_{k=0}^n \\binom{n}{k} x^{n-k} y^k",
    commonTraps: ["Off-by-one errors when finding the (r+1)th term"],
  },
  {
    id: "jee-concept-dot-product",
    subjectId: "Mathematics",
    chapterId: "math-vectors",
    label: "Dot Product (Scalar Product)",
    summary: "An algebraic operation that takes two equal-length sequences of numbers and returns a single number.",
    importance: "high",
    category: "Vectors",
    formula: "\\mathbf{a} \\cdot \\mathbf{b} = |\\mathbf{a}| |\\mathbf{b}| \\cos \\theta",
    commonTraps: ["Confusing the dot product (scalar) with the cross product (vector)"],
  },
  {
    id: "jee-concept-hyperbola-eccentricity",
    subjectId: "Mathematics",
    chapterId: "math-coordinate",
    label: "Eccentricity of a Hyperbola",
    summary: "A measure of how much the conic section deviates from being circular.",
    importance: "high",
    category: "Coordinate Geometry",
    formula: "e = \\sqrt{1 + \\frac{b^2}{a^2}}",
    commonTraps: ["Using the ellipse formula (1 - b^2/a^2) instead of the hyperbola formula"],
  },
]
