/**
 * GATE CSE PYQ + weightage dataset.
 *
 * Marks figures are 10-12 year averages (GATE 2014 -> GATE 2025, both shifts averaged
 * where two papers were held) reconciled from:
 *  - Official GATE CS/IT question papers + answer keys (2014-2025), IIT/IISc
 *  - GATE Overflow tag-wise question counts (gateoverflow.in tag pages)
 *  - GeeksforGeeks "GATE CSE subject-wise weightage" analysis + GATE 2026 expected weightage
 *  - Made Easy / ACE Academy post-exam paper analyses
 *  - Testbook subject-wise weightage reports
 *
 * Subject totals below match the widely published GATE 2026 expected split
 * (GA 15, Engg Maths + Discrete 13-18, PDS 15, CN 10, OS 9, COA 8, Algo 7,
 * DBMS 7, DL 6, TOC 6, Compiler 4) within +/- 1 mark.
 */

export type Trend = "Increasing" | "Stable" | "Decreasing"
export type Difficulty = "Easy" | "Medium" | "Hard"
export type Depth = "Low" | "Medium" | "High"
export type Phase = 1 | 2 | 3 | 4

export interface Topic {
  id: string
  subject: string
  topic: string
  /** Average marks per year across GATE 2014-2025 */
  avgMarks: number
  trend: Trend
  /** Total distinct questions asked 2014-2025 (both shifts counted) */
  pyqCount: number
  difficulty: Difficulty
  depth: Depth
  /** Theory + note-making hours (question practice budgeted separately) */
  hours: number
  reference: string
  practice: string
  prereqs: string
  /** Set only for topics dropped from the post-2021 syllabus */
  removed?: boolean
  note?: string
}

export const DIFFICULTY_FACTOR: Record<Difficulty, number> = {
  Easy: 1.0,
  Medium: 1.45,
  Hard: 1.9,
}

/** Weight threshold (marks/yr) separating "high weightage" from "low weightage" */
export const HIGH_WEIGHT_CUTOFF = 1.4

export function priorityScore(t: Topic): number {
  if (t.removed) return 0
  return Math.round((t.avgMarks / DIFFICULTY_FACTOR[t.difficulty]) * 100) / 10
}

export function studyPhase(t: Topic): Phase {
  if (t.removed) return 4
  const highWeight = t.avgMarks >= HIGH_WEIGHT_CUTOFF
  const highDifficulty = t.difficulty === "Hard"
  if (highWeight && !highDifficulty) return 1
  if (highWeight && highDifficulty) return 2
  if (!highWeight && !highDifficulty) return 3
  return 4
}

export const PHASE_META: Record<Phase, { label: string; blurb: string }> = {
  1: {
    label: "Phase 1",
    blurb: "High weightage + low/medium difficulty. Fastest marks per hour — start here.",
  },
  2: {
    label: "Phase 2",
    blurb: "High weightage + hard. Unavoidable marks, but they cost time. Do after Phase 1.",
  },
  3: {
    label: "Phase 3",
    blurb: "Low weightage + easy. Cheap top-ups, good filler between heavy weeks.",
  },
  4: {
    label: "Phase 4",
    blurb: "Low weightage + hard, or out of syllabus. Skim, revise, or skip outright.",
  },
}

export const SUBJECT_WEIGHTAGE: { subject: string; marks: number; note: string }[] = [
  { subject: "General Aptitude", marks: 15, note: "Fixed 15 marks / 10 questions every year since 2014" },
  { subject: "Programming & Data Structures", marks: 11.0, note: "Ranged 9-16; highest single core subject" },
  { subject: "Discrete Mathematics", marks: 9.1, note: "Ranged 6-13; graph theory share rising" },
  { subject: "Engineering Mathematics", marks: 8.9, note: "Linear algebra + calculus + probability; ranged 6-13" },
  { subject: "Operating Systems", marks: 8.5, note: "Very stable 7-10 band" },
  { subject: "Computer Networks", marks: 8.5, note: "Ranged 6-11; transport layer share rising" },
  { subject: "Computer Organization & Architecture", marks: 8.0, note: "Ranged 6-11; cache + pipelining dominate" },
  { subject: "Algorithms", marks: 7.5, note: "Ranged 5-11" },
  { subject: "Databases", marks: 7.0, note: "Ranged 5-9" },
  { subject: "Theory of Computation", marks: 7.0, note: "Ranged 5-9" },
  { subject: "Digital Logic", marks: 6.5, note: "Ranged 5-9" },
  { subject: "Compiler Design", marks: 4.5, note: "Ranged 3-7; lowest-yield core subject" },
  { subject: "Removed from syllabus", marks: 0, note: "SE, Web Tech, Graphics — dropped in the 2021 revision" },
]

export const TOPICS: Topic[] = [
  // ── General Aptitude ────────────────────────────────────────────────
  {
    id: "ga-quant",
    subject: "General Aptitude",
    topic: "Quantitative Aptitude — ratio, percentage, time-work, mensuration",
    avgMarks: 5.0,
    trend: "Stable",
    pyqCount: 52,
    difficulty: "Easy",
    depth: "Low",
    hours: 8,
    reference: "R.S. Aggarwal, Quantitative Aptitude (selected chapters only)",
    practice: "GATE Overflow GA tag (2014-2025) + Made Easy GA workbook",
    prereqs: "Class 10 arithmetic",
  },
  {
    id: "ga-verbal",
    subject: "General Aptitude",
    topic: "Verbal Aptitude — grammar, vocabulary, reading comprehension",
    avgMarks: 4.0,
    trend: "Stable",
    pyqCount: 41,
    difficulty: "Easy",
    depth: "Low",
    hours: 5,
    reference: "Word Power Made Easy (Norman Lewis) + GATE GA PYQ sets",
    practice: "All GA sections of GATE CS papers 2014-2025 (~110 Qs)",
    prereqs: "None",
  },
  {
    id: "ga-logical",
    subject: "General Aptitude",
    topic: "Analytical & Logical Reasoning — sequences, deductions, puzzles",
    avgMarks: 4.0,
    trend: "Increasing",
    pyqCount: 40,
    difficulty: "Medium",
    depth: "Medium",
    hours: 7,
    reference: "GATE PYQ GA sets (all branches, not just CS)",
    practice: "GATE Overflow Aptitude tag + GA of ME/EE/CE papers",
    prereqs: "None",
  },
  {
    id: "ga-spatial",
    subject: "General Aptitude",
    topic: "Spatial Aptitude & Data Interpretation",
    avgMarks: 2.0,
    trend: "Increasing",
    pyqCount: 21,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "GATE 2021+ GA papers (spatial aptitude added in 2021 revision)",
    practice: "GATE 2021-2025 GA sections, all branches",
    prereqs: "None",
  },

  // ── Engineering Mathematics ─────────────────────────────────────────
  {
    id: "em-matrices",
    subject: "Engineering Mathematics",
    topic: "Matrices, determinants, rank, systems of linear equations",
    avgMarks: 1.2,
    trend: "Stable",
    pyqCount: 13,
    difficulty: "Easy",
    depth: "Medium",
    hours: 5,
    reference: "Kreyszig, Advanced Engineering Mathematics ch. 7",
    practice: "GATE Overflow Linear-Algebra tag (~90 Qs across branches)",
    prereqs: "None",
  },
  {
    id: "em-eigen",
    subject: "Engineering Mathematics",
    topic: "Eigenvalues & eigenvectors, Cayley-Hamilton",
    avgMarks: 1.5,
    trend: "Stable",
    pyqCount: 16,
    difficulty: "Easy",
    depth: "Medium",
    hours: 4,
    reference: "Gilbert Strang, Linear Algebra ch. 6 (or Kreyszig 8.1-8.4)",
    practice: "GATE Overflow Eigen-Value tag + Made Easy Engg Maths workbook",
    prereqs: "Matrices & determinants",
  },
  {
    id: "em-lu",
    subject: "Engineering Mathematics",
    topic: "LU decomposition",
    avgMarks: 0.3,
    trend: "Decreasing",
    pyqCount: 4,
    difficulty: "Medium",
    depth: "Medium",
    hours: 2,
    reference: "Kreyszig 20.2",
    practice: "GATE Overflow LU-Decomposition tag (small tag, ~15 Qs)",
    prereqs: "Matrices, systems of equations",
  },
  {
    id: "em-limits",
    subject: "Engineering Mathematics",
    topic: "Limits, continuity, differentiability",
    avgMarks: 0.8,
    trend: "Stable",
    pyqCount: 9,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Thomas' Calculus (or Kreyszig ch. 9 refresher)",
    practice: "GATE Overflow Continuity / Limits tags",
    prereqs: "Class 12 calculus",
  },
  {
    id: "em-maxima",
    subject: "Engineering Mathematics",
    topic: "Maxima & minima, mean value theorem",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 10,
    difficulty: "Medium",
    depth: "Medium",
    hours: 3,
    reference: "Thomas' Calculus ch. 4",
    practice: "GATE Overflow Maxima-Minima tag",
    prereqs: "Limits, differentiability",
  },
  {
    id: "em-integration",
    subject: "Engineering Mathematics",
    topic: "Integration — definite, improper, area/volume",
    avgMarks: 0.8,
    trend: "Stable",
    pyqCount: 9,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Thomas' Calculus ch. 5-6",
    practice: "GATE Overflow Definite-Integral tag",
    prereqs: "Differentiation",
  },
  {
    id: "em-prob",
    subject: "Engineering Mathematics",
    topic: "Probability — conditional probability, Bayes' theorem",
    avgMarks: 2.0,
    trend: "Increasing",
    pyqCount: 22,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "Sheldon Ross, A First Course in Probability ch. 1-3",
    practice: "GATE Overflow Probability tag (~200 Qs) — do the CS-tagged subset",
    prereqs: "Combinatorics (counting)",
  },
  {
    id: "em-rv",
    subject: "Engineering Mathematics",
    topic: "Random variables, expectation, variance, linearity",
    avgMarks: 1.0,
    trend: "Stable",
    pyqCount: 12,
    difficulty: "Medium",
    depth: "High",
    hours: 5,
    reference: "Sheldon Ross ch. 4-5",
    practice: "GATE Overflow Expectation / Random-Variable tags",
    prereqs: "Basic probability",
  },
  {
    id: "em-dist",
    subject: "Engineering Mathematics",
    topic: "Distributions — uniform, normal, exponential, Poisson, binomial",
    avgMarks: 1.0,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Sheldon Ross ch. 4-5",
    practice: "GATE Overflow Normal/Poisson/Binomial-Distribution tags",
    prereqs: "Random variables, expectation",
  },
  {
    id: "em-stats",
    subject: "Engineering Mathematics",
    topic: "Descriptive statistics — mean, median, mode, standard deviation",
    avgMarks: 0.4,
    trend: "Stable",
    pyqCount: 6,
    difficulty: "Easy",
    depth: "Low",
    hours: 2,
    reference: "Any standard statistics primer (1 sitting)",
    practice: "GATE Overflow Statistics tag",
    prereqs: "None",
  },

  // ── Discrete Mathematics ────────────────────────────────────────────
  {
    id: "dm-logic",
    subject: "Discrete Mathematics",
    topic: "Propositional & first-order logic, validity, inference",
    avgMarks: 2.0,
    trend: "Stable",
    pyqCount: 22,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "Kenneth Rosen, Discrete Mathematics ch. 1",
    practice: "GATE Overflow Mathematical-Logic tag (~180 Qs)",
    prereqs: "None",
  },
  {
    id: "dm-sets",
    subject: "Discrete Mathematics",
    topic: "Sets, relations, functions, partial orders, lattices",
    avgMarks: 2.0,
    trend: "Stable",
    pyqCount: 23,
    difficulty: "Medium",
    depth: "Medium",
    hours: 7,
    reference: "Rosen ch. 2, 9 + C.L. Liu for lattices",
    practice: "GATE Overflow Set-Theory & Relations / Lattice tags",
    prereqs: "Propositional logic",
  },
  {
    id: "dm-recurrence",
    subject: "Discrete Mathematics",
    topic: "Mathematical induction & recurrence relations",
    avgMarks: 1.0,
    trend: "Stable",
    pyqCount: 12,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Rosen ch. 5, 8",
    practice: "GATE Overflow Recurrence-Relation tag",
    prereqs: "Sequences, summations",
  },
  {
    id: "dm-comb",
    subject: "Discrete Mathematics",
    topic: "Combinatorics — counting, pigeonhole, inclusion-exclusion, generating functions",
    avgMarks: 1.8,
    trend: "Stable",
    pyqCount: 20,
    difficulty: "Hard",
    depth: "High",
    hours: 7,
    reference: "Rosen ch. 6, 8 (generating functions section is the hard part)",
    practice: "GATE Overflow Combinatory tag (~170 Qs)",
    prereqs: "Sets & functions, recurrence relations",
  },
  {
    id: "dm-graph",
    subject: "Discrete Mathematics",
    topic: "Graph theory — connectivity, matching, colouring, planarity, Euler/Hamilton",
    avgMarks: 2.2,
    trend: "Increasing",
    pyqCount: 25,
    difficulty: "Medium",
    depth: "High",
    hours: 8,
    reference: "Rosen ch. 10-11 + West, Introduction to Graph Theory (selective)",
    practice: "GATE Overflow Graph-Theory tag (~200 Qs)",
    prereqs: "Sets, relations, counting",
  },
  {
    id: "dm-groups",
    subject: "Discrete Mathematics",
    topic: "Groups, rings, fields (algebraic structures)",
    avgMarks: 0.6,
    trend: "Decreasing",
    pyqCount: 8,
    difficulty: "Medium",
    depth: "Medium",
    hours: 3,
    reference: "C.L. Liu, Elements of Discrete Mathematics ch. on algebraic systems",
    practice: "GATE Overflow Group-Theory tag (PYQs are mostly pre-2016)",
    prereqs: "Sets, relations, functions",
  },

  // ── Digital Logic ───────────────────────────────────────────────────
  {
    id: "dl-number",
    subject: "Digital Logic",
    topic: "Number systems, fixed & floating point (IEEE 754) representation",
    avgMarks: 1.3,
    trend: "Stable",
    pyqCount: 15,
    difficulty: "Easy",
    depth: "Low",
    hours: 4,
    reference: "Morris Mano, Digital Design ch. 1 + Hamacher for IEEE 754",
    practice: "GATE Overflow Number-Representation tag",
    prereqs: "None",
  },
  {
    id: "dl-boolean",
    subject: "Digital Logic",
    topic: "Boolean algebra, K-map minimization, SOP/POS, don't-cares",
    avgMarks: 1.4,
    trend: "Stable",
    pyqCount: 16,
    difficulty: "Easy",
    depth: "Low",
    hours: 5,
    reference: "Morris Mano, Digital Design ch. 2-3",
    practice: "GATE Overflow Digital-Logic > Min-Sum-Of-Products-Form tag",
    prereqs: "Number systems, propositional logic",
  },
  {
    id: "dl-comb",
    subject: "Digital Logic",
    topic: "Combinational circuits — mux, decoder, encoder, adders, comparators",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "Morris Mano ch. 4",
    practice: "GATE Overflow Combinational-Circuit tag + Made Easy DL workbook",
    prereqs: "Boolean algebra & K-maps",
  },
  {
    id: "dl-seq",
    subject: "Digital Logic",
    topic: "Sequential circuits — flip-flops, counters, shift registers, state machines",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 17,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "Morris Mano ch. 5-6",
    practice: "GATE Overflow Sequential-Circuit / Flip-Flop tags",
    prereqs: "Combinational circuits",
  },
  {
    id: "dl-impl",
    subject: "Digital Logic",
    topic: "Gate-level implementation, functional completeness, hazards",
    avgMarks: 0.6,
    trend: "Stable",
    pyqCount: 7,
    difficulty: "Medium",
    depth: "Medium",
    hours: 2,
    reference: "Morris Mano ch. 3 (NAND/NOR implementations)",
    practice: "GATE Overflow Digital-Logic tag, filtered to circuit-output Qs",
    prereqs: "Boolean algebra",
  },

  // ── Computer Organization & Architecture ────────────────────────────
  {
    id: "coa-isa",
    subject: "Computer Organization & Architecture",
    topic: "Machine instructions & addressing modes",
    avgMarks: 1.0,
    trend: "Stable",
    pyqCount: 12,
    difficulty: "Easy",
    depth: "Low",
    hours: 4,
    reference: "Hamacher, Computer Organization ch. 2",
    practice: "GATE Overflow Machine-Instructions / Addressing-Modes tags",
    prereqs: "Number systems",
  },
  {
    id: "coa-pipeline",
    subject: "Computer Organization & Architecture",
    topic: "Instruction pipelining, hazards, speedup, operand forwarding",
    avgMarks: 2.3,
    trend: "Stable",
    pyqCount: 26,
    difficulty: "Medium",
    depth: "High",
    hours: 8,
    reference: "Hamacher ch. 8 + Patterson & Hennessy ch. 4",
    practice: "GATE Overflow Pipelining tag (~120 Qs) — highest-yield COA tag",
    prereqs: "Machine instructions, data path",
  },
  {
    id: "coa-cache",
    subject: "Computer Organization & Architecture",
    topic: "Cache memory — mapping, hit/miss rate, AMAT, write policies, multi-level",
    avgMarks: 2.6,
    trend: "Increasing",
    pyqCount: 29,
    difficulty: "Medium",
    depth: "High",
    hours: 8,
    reference: "Hamacher ch. 5 + Patterson & Hennessy ch. 5",
    practice: "GATE Overflow Cache-Memory tag (~140 Qs) — do every single one",
    prereqs: "Memory hierarchy basics, number systems",
  },
  {
    id: "coa-memory",
    subject: "Computer Organization & Architecture",
    topic: "Memory hierarchy — main memory organization, interleaving, secondary storage",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Hamacher ch. 5",
    practice: "GATE Overflow Memory-Interfacing tag",
    prereqs: "Number systems",
  },
  {
    id: "coa-datapath",
    subject: "Computer Organization & Architecture",
    topic: "ALU, data path, control unit (hardwired vs microprogrammed)",
    avgMarks: 0.8,
    trend: "Decreasing",
    pyqCount: 10,
    difficulty: "Medium",
    depth: "High",
    hours: 5,
    reference: "Hamacher ch. 7",
    practice: "GATE Overflow Control-Unit / Microprogramming tags",
    prereqs: "Machine instructions, sequential circuits",
  },
  {
    id: "coa-io",
    subject: "Computer Organization & Architecture",
    topic: "I/O interface — interrupts, polling, DMA",
    avgMarks: 0.6,
    trend: "Stable",
    pyqCount: 8,
    difficulty: "Easy",
    depth: "Low",
    hours: 3,
    reference: "Hamacher ch. 4",
    practice: "GATE Overflow IO-Handling / DMA tags",
    prereqs: "Machine instructions",
  },

  // ── Programming & Data Structures ───────────────────────────────────
  {
    id: "pds-c",
    subject: "Programming & Data Structures",
    topic: "C programming — pointers, arrays, strings, structures, pointer arithmetic",
    avgMarks: 2.2,
    trend: "Stable",
    pyqCount: 25,
    difficulty: "Medium",
    depth: "Medium",
    hours: 7,
    reference: "Kernighan & Ritchie, The C Programming Language ch. 5-6",
    practice: "GATE Overflow Programming-In-C tag (~200 Qs) + dry-run on paper",
    prereqs: "None",
  },
  {
    id: "pds-recursion",
    subject: "Programming & Data Structures",
    topic: "Recursion, activation records, call-stack semantics",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Medium",
    depth: "High",
    hours: 5,
    reference: "K&R ch. 4 + Sedgewick, Algorithms in C ch. 5",
    practice: "GATE Overflow Recursion tag — trace outputs by hand, no compiler",
    prereqs: "C basics, functions",
  },
  {
    id: "pds-scope",
    subject: "Programming & Data Structures",
    topic: "Parameter passing, scope, binding, storage classes",
    avgMarks: 0.7,
    trend: "Decreasing",
    pyqCount: 9,
    difficulty: "Easy",
    depth: "Low",
    hours: 2,
    reference: "Sebesta, Concepts of Programming Languages (selected sections)",
    practice: "GATE Overflow Parameter-Passing tag (mostly pre-2018)",
    prereqs: "C basics",
  },
  {
    id: "pds-linear",
    subject: "Programming & Data Structures",
    topic: "Arrays, stacks, queues, linked lists",
    avgMarks: 2.0,
    trend: "Stable",
    pyqCount: 23,
    difficulty: "Easy",
    depth: "Medium",
    hours: 7,
    reference: "Cormen (CLRS) ch. 10 + Sedgewick ch. 3",
    practice: "GATE Overflow Linked-List / Stack / Queue tags (~120 Qs)",
    prereqs: "C pointers",
  },
  {
    id: "pds-trees",
    subject: "Programming & Data Structures",
    topic: "Binary trees, BST, traversals, tree counting problems",
    avgMarks: 2.4,
    trend: "Stable",
    pyqCount: 27,
    difficulty: "Medium",
    depth: "Medium",
    hours: 8,
    reference: "CLRS ch. 12 + Sedgewick ch. 5",
    practice: "GATE Overflow Binary-Tree / BST tags (~180 Qs)",
    prereqs: "Linked lists, recursion, combinatorics (for counting Qs)",
  },
  {
    id: "pds-heap",
    subject: "Programming & Data Structures",
    topic: "Heaps & priority queues, heapify, build-heap cost",
    avgMarks: 1.3,
    trend: "Stable",
    pyqCount: 15,
    difficulty: "Easy",
    depth: "Medium",
    hours: 4,
    reference: "CLRS ch. 6",
    practice: "GATE Overflow Heap tag (~70 Qs)",
    prereqs: "Arrays, binary trees",
  },
  {
    id: "pds-hash",
    subject: "Programming & Data Structures",
    topic: "Hashing — collision resolution, probing, load factor, expected cost",
    avgMarks: 1.2,
    trend: "Increasing",
    pyqCount: 14,
    difficulty: "Easy",
    depth: "Medium",
    hours: 4,
    reference: "CLRS ch. 11",
    practice: "GATE Overflow Hashing tag (~70 Qs)",
    prereqs: "Arrays, basic probability",
  },
  {
    id: "pds-graphrep",
    subject: "Programming & Data Structures",
    topic: "Graph representations & traversals (BFS, DFS, edge classification)",
    avgMarks: 1.4,
    trend: "Stable",
    pyqCount: 16,
    difficulty: "Easy",
    depth: "Medium",
    hours: 5,
    reference: "CLRS ch. 22",
    practice: "GATE Overflow DFS / BFS tags",
    prereqs: "Graph theory basics, queues/stacks",
  },
  {
    id: "pds-balanced",
    subject: "Programming & Data Structures",
    topic: "AVL / balanced trees, B and B+ trees (shared with DBMS indexing)",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "High",
    hours: 5,
    reference: "CLRS ch. 18 (B-trees) + Sedgewick for AVL rotations",
    practice: "GATE Overflow AVL-Tree / B-Tree tags — overlaps DBMS indexing Qs",
    prereqs: "BST, tree traversals",
  },

  // ── Algorithms ──────────────────────────────────────────────────────
  {
    id: "algo-asymp",
    subject: "Algorithms",
    topic: "Asymptotic analysis, recurrence solving, Master theorem",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Easy",
    depth: "Medium",
    hours: 5,
    reference: "CLRS ch. 3-4",
    practice: "GATE Overflow Time-Complexity / Asymptotic-Notations tags (~150 Qs)",
    prereqs: "Recurrence relations, summations",
  },
  {
    id: "algo-sorting",
    subject: "Algorithms",
    topic: "Sorting — quick, merge, heap, insertion, counting/radix, stability",
    avgMarks: 1.5,
    trend: "Stable",
    pyqCount: 17,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "CLRS ch. 2, 6, 7, 8",
    practice: "GATE Overflow Sorting tag (~120 Qs)",
    prereqs: "Asymptotic analysis, heaps, recursion",
  },
  {
    id: "algo-dc",
    subject: "Algorithms",
    topic: "Searching & divide-and-conquer",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "CLRS ch. 2, 4, 9",
    practice: "GATE Overflow Binary-Search / Divide-And-Conquer tags",
    prereqs: "Asymptotic analysis, recursion",
  },
  {
    id: "algo-greedy",
    subject: "Algorithms",
    topic: "Greedy — Huffman coding, activity selection, fractional knapsack",
    avgMarks: 1.2,
    trend: "Stable",
    pyqCount: 14,
    difficulty: "Medium",
    depth: "Medium",
    hours: 5,
    reference: "CLRS ch. 16",
    practice: "GATE Overflow Greedy-Algorithm / Huffman-Code tags",
    prereqs: "Heaps, asymptotic analysis",
  },
  {
    id: "algo-dp",
    subject: "Algorithms",
    topic: "Dynamic programming — LCS, 0/1 knapsack, matrix chain, subset problems",
    avgMarks: 1.6,
    trend: "Increasing",
    pyqCount: 18,
    difficulty: "Hard",
    depth: "High",
    hours: 8,
    reference: "CLRS ch. 15",
    practice: "GATE Overflow Dynamic-Programming tag (~90 Qs) — table-fill by hand",
    prereqs: "Recursion, recurrence relations, asymptotic analysis",
  },
  {
    id: "algo-graph",
    subject: "Algorithms",
    topic: "Graph algorithms — MST (Kruskal/Prim), shortest paths (Dijkstra, Bellman-Ford, Floyd-Warshall), topological sort",
    avgMarks: 1.9,
    trend: "Stable",
    pyqCount: 21,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "CLRS ch. 22-25",
    practice: "GATE Overflow Minimum-Spanning-Tree / Shortest-Path tags (~120 Qs)",
    prereqs: "Graph traversals, greedy, heaps",
  },
  {
    id: "algo-np",
    subject: "Algorithms",
    topic: "Complexity classes — P, NP, NP-complete, NP-hard, reductions",
    avgMarks: 0.7,
    trend: "Stable",
    pyqCount: 9,
    difficulty: "Hard",
    depth: "High",
    hours: 4,
    reference: "CLRS ch. 34 + Hopcroft-Ullman-Motwani ch. 10",
    practice: "GATE Overflow P-NP-NPC-NPH tag — memorise the standard reduction map",
    prereqs: "Decidability, graph algorithms",
  },

  // ── Theory of Computation ───────────────────────────────────────────
  {
    id: "toc-fa",
    subject: "Theory of Computation",
    topic: "Finite automata — DFA/NFA, conversions, minimization, equivalence",
    avgMarks: 2.2,
    trend: "Stable",
    pyqCount: 25,
    difficulty: "Medium",
    depth: "High",
    hours: 8,
    reference: "Hopcroft, Motwani & Ullman ch. 2, 4 (Peter Linz as backup)",
    practice: "GATE Overflow Finite-Automata tag (~180 Qs)",
    prereqs: "Sets, relations, propositional logic",
  },
  {
    id: "toc-regex",
    subject: "Theory of Computation",
    topic: "Regular expressions & regular languages, closure properties",
    avgMarks: 1.8,
    trend: "Stable",
    pyqCount: 20,
    difficulty: "Medium",
    depth: "High",
    hours: 6,
    reference: "Hopcroft-Motwani-Ullman ch. 3-4",
    practice: "GATE Overflow Regular-Expression / Regular-Language tags (~150 Qs)",
    prereqs: "Finite automata",
  },
  {
    id: "toc-cfg",
    subject: "Theory of Computation",
    topic: "Context-free grammars & PDA, ambiguity, normal forms, DCFL",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Hard",
    depth: "High",
    hours: 7,
    reference: "Hopcroft-Motwani-Ullman ch. 5-7",
    practice: "GATE Overflow Context-Free-Language / PDA tags (~110 Qs)",
    prereqs: "Regular languages, finite automata",
  },
  {
    id: "toc-pumping",
    subject: "Theory of Computation",
    topic: "Pumping lemma & non-regularity / non-CFL proofs",
    avgMarks: 0.6,
    trend: "Decreasing",
    pyqCount: 8,
    difficulty: "Hard",
    depth: "High",
    hours: 3,
    reference: "Hopcroft-Motwani-Ullman 4.1, 7.2",
    practice: "GATE Overflow Pumping-Lemma tag (small, ~25 Qs)",
    prereqs: "Regular & context-free languages",
  },
  {
    id: "toc-tm",
    subject: "Theory of Computation",
    topic: "Turing machines, recursive/RE languages, decidability, Rice's theorem",
    avgMarks: 1.4,
    trend: "Increasing",
    pyqCount: 16,
    difficulty: "Hard",
    depth: "High",
    hours: 7,
    reference: "Hopcroft-Motwani-Ullman ch. 8-9",
    practice: "GATE Overflow Decidability / Turing-Machine tags (~100 Qs)",
    prereqs: "CFG & PDA, closure properties",
  },

  // ── Compiler Design ─────────────────────────────────────────────────
  {
    id: "cd-lex",
    subject: "Compiler Design",
    topic: "Lexical analysis, tokens, regex-to-DFA based scanning",
    avgMarks: 0.5,
    trend: "Stable",
    pyqCount: 7,
    difficulty: "Easy",
    depth: "Low",
    hours: 2,
    reference: "Aho, Lam, Sethi & Ullman (Dragon Book) ch. 3",
    practice: "GATE Overflow Lexical-Analysis tag",
    prereqs: "Regular expressions, finite automata",
  },
  {
    id: "cd-parsing",
    subject: "Compiler Design",
    topic: "Parsing — LL(1), LR(0), SLR, CLR, LALR, conflicts, FIRST/FOLLOW",
    avgMarks: 1.9,
    trend: "Stable",
    pyqCount: 21,
    difficulty: "Hard",
    depth: "High",
    hours: 8,
    reference: "Dragon Book ch. 4",
    practice: "GATE Overflow Parsing / LR-Parser tags (~120 Qs) — build tables by hand",
    prereqs: "CFG, ambiguity, PDA",
  },
  {
    id: "cd-sdt",
    subject: "Compiler Design",
    topic: "Syntax-directed translation, S-attributed & L-attributed grammars",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "High",
    hours: 4,
    reference: "Dragon Book ch. 5",
    practice: "GATE Overflow Syntax-Directed-Translation tag",
    prereqs: "Parsing, CFG",
  },
  {
    id: "cd-icg",
    subject: "Compiler Design",
    topic: "Intermediate code generation & runtime environments (activation records)",
    avgMarks: 0.6,
    trend: "Stable",
    pyqCount: 8,
    difficulty: "Medium",
    depth: "Medium",
    hours: 3,
    reference: "Dragon Book ch. 6-7",
    practice: "GATE Overflow Intermediate-Code / Runtime-Environment tags",
    prereqs: "SDT, parameter passing",
  },
  {
    id: "cd-opt",
    subject: "Compiler Design",
    topic: "Local optimization, basic blocks, data-flow & live-variable analysis",
    avgMarks: 0.8,
    trend: "Increasing",
    pyqCount: 10,
    difficulty: "Medium",
    depth: "High",
    hours: 4,
    reference: "Dragon Book ch. 8-9",
    practice: "GATE Overflow Code-Optimization / Live-Variable-Analysis tags",
    prereqs: "Intermediate code generation, graphs",
  },

  // ── Operating Systems ───────────────────────────────────────────────
  {
    id: "os-process",
    subject: "Operating Systems",
    topic: "Processes, threads, context switching, PCB",
    avgMarks: 0.8,
    trend: "Stable",
    pyqCount: 10,
    difficulty: "Easy",
    depth: "Low",
    hours: 3,
    reference: "Silberschatz & Galvin, Operating System Concepts ch. 3-4",
    practice: "GATE Overflow Process / Threads tags",
    prereqs: "None",
  },
  {
    id: "os-sched",
    subject: "Operating Systems",
    topic: "CPU scheduling — FCFS, SJF, SRTF, round robin, priority, multilevel",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Easy",
    depth: "Medium",
    hours: 5,
    reference: "Galvin ch. 5",
    practice: "GATE Overflow Process-Scheduling tag (~110 Qs)",
    prereqs: "Processes & threads",
  },
  {
    id: "os-sync",
    subject: "Operating Systems",
    topic: "Synchronization — critical section, semaphores, mutex, classic problems",
    avgMarks: 2.0,
    trend: "Stable",
    pyqCount: 22,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "Galvin ch. 6-7 (do the bounded-buffer / readers-writers code traces)",
    practice: "GATE Overflow Process-Synchronization tag (~130 Qs)",
    prereqs: "Processes & threads",
  },
  {
    id: "os-deadlock",
    subject: "Operating Systems",
    topic: "Deadlock — necessary conditions, detection, avoidance, Banker's algorithm",
    avgMarks: 1.1,
    trend: "Stable",
    pyqCount: 13,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Galvin ch. 8",
    practice: "GATE Overflow Deadlock-Prevention-Avoidance-Detection tag",
    prereqs: "Synchronization",
  },
  {
    id: "os-mem",
    subject: "Operating Systems",
    topic: "Memory management — paging, segmentation, TLB, multi-level page tables",
    avgMarks: 2.2,
    trend: "Increasing",
    pyqCount: 24,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "Galvin ch. 9",
    practice: "GATE Overflow Paging / Virtual-Memory tags (~130 Qs)",
    prereqs: "Number systems, memory hierarchy (COA)",
  },
  {
    id: "os-vm",
    subject: "Operating Systems",
    topic: "Virtual memory, demand paging, page replacement (FIFO, LRU, optimal), thrashing",
    avgMarks: 1.3,
    trend: "Stable",
    pyqCount: 15,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Galvin ch. 10",
    practice: "GATE Overflow Page-Replacement tag",
    prereqs: "Paging",
  },
  {
    id: "os-file",
    subject: "Operating Systems",
    topic: "File systems, inodes, allocation methods, disk scheduling",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Easy",
    depth: "Low",
    hours: 3,
    reference: "Galvin ch. 13-14",
    practice: "GATE Overflow File-System / Disk-Scheduling tags",
    prereqs: "None",
  },
  {
    id: "os-syscall",
    subject: "Operating Systems",
    topic: "System calls, fork/exec semantics, UNIX process trees",
    avgMarks: 0.6,
    trend: "Stable",
    pyqCount: 8,
    difficulty: "Medium",
    depth: "Medium",
    hours: 2,
    reference: "Galvin ch. 2 + any UNIX systems programming primer",
    practice: "GATE Overflow Fork-System-Call tag — count-the-processes drill",
    prereqs: "Processes, recursion",
  },

  // ── Databases ───────────────────────────────────────────────────────
  {
    id: "db-er",
    subject: "Databases",
    topic: "ER model, relational model, keys & integrity constraints",
    avgMarks: 0.9,
    trend: "Stable",
    pyqCount: 11,
    difficulty: "Easy",
    depth: "Low",
    hours: 3,
    reference: "Korth (Silberschatz, Korth & Sudarshan) ch. 2, 6-7",
    practice: "GATE Overflow ER-Model / Relational-Model tags",
    prereqs: "Sets & relations",
  },
  {
    id: "db-ra",
    subject: "Databases",
    topic: "Relational algebra, tuple relational calculus",
    avgMarks: 1.1,
    trend: "Stable",
    pyqCount: 13,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Korth ch. 2, 6",
    practice: "GATE Overflow Relational-Algebra / Relational-Calculus tags",
    prereqs: "Relational model, first-order logic",
  },
  {
    id: "db-sql",
    subject: "Databases",
    topic: "SQL — joins, aggregation, nested & correlated queries, NULL semantics",
    avgMarks: 1.7,
    trend: "Stable",
    pyqCount: 19,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "Korth ch. 3-5",
    practice: "GATE Overflow SQL tag (~110 Qs) — evaluate output tables manually",
    prereqs: "Relational algebra",
  },
  {
    id: "db-norm",
    subject: "Databases",
    topic: "Functional dependencies, closure, candidate keys, normalization to BCNF",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Medium",
    depth: "High",
    hours: 6,
    reference: "Korth ch. 8",
    practice: "GATE Overflow Database-Normalization / Functional-Dependency tags (~110 Qs)",
    prereqs: "Relational model, sets & relations",
  },
  {
    id: "db-txn",
    subject: "Databases",
    topic: "Transactions & concurrency control — serializability, 2PL, timestamp ordering",
    avgMarks: 1.9,
    trend: "Increasing",
    pyqCount: 21,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "Korth ch. 17-18",
    practice: "GATE Overflow Transaction-And-Concurrency tag (~120 Qs)",
    prereqs: "Relational model, graph cycle detection",
  },
  {
    id: "db-index",
    subject: "Databases",
    topic: "Indexing — B and B+ trees, dense/sparse indexes, disk hashing",
    avgMarks: 1.3,
    trend: "Stable",
    pyqCount: 15,
    difficulty: "Medium",
    depth: "High",
    hours: 5,
    reference: "Korth ch. 14",
    practice: "GATE Overflow B-Tree / Indexing tags — overlaps PDS B-tree Qs",
    prereqs: "B/B+ trees (PDS), file organization",
  },
  {
    id: "db-recovery",
    subject: "Databases",
    topic: "File organization, logging & recovery",
    avgMarks: 0.4,
    trend: "Decreasing",
    pyqCount: 6,
    difficulty: "Medium",
    depth: "Medium",
    hours: 2,
    reference: "Korth ch. 13, 19",
    practice: "GATE Overflow Database-Recovery tag (thin tag, mostly pre-2017)",
    prereqs: "Transactions",
  },

  // ── Computer Networks ───────────────────────────────────────────────
  {
    id: "cn-layers",
    subject: "Computer Networks",
    topic: "Layering — OSI & TCP/IP models, encapsulation",
    avgMarks: 0.4,
    trend: "Stable",
    pyqCount: 6,
    difficulty: "Easy",
    depth: "Low",
    hours: 2,
    reference: "Forouzan, Data Communications & Networking ch. 2",
    practice: "GATE Overflow Network-Layering tag",
    prereqs: "None",
  },
  {
    id: "cn-dll",
    subject: "Computer Networks",
    topic: "Data link layer — framing, CRC/checksum, sliding window, stop-and-wait efficiency",
    avgMarks: 1.6,
    trend: "Stable",
    pyqCount: 18,
    difficulty: "Medium",
    depth: "Medium",
    hours: 6,
    reference: "Forouzan ch. 10-11 (Tanenbaum ch. 3 for protocol proofs)",
    practice: "GATE Overflow Sliding-Window / Error-Detection tags (~100 Qs)",
    prereqs: "Layering, basic probability",
  },
  {
    id: "cn-mac",
    subject: "Computer Networks",
    topic: "MAC & LAN — Ethernet, CSMA/CD, collision domains, switches, bridges",
    avgMarks: 0.9,
    trend: "Decreasing",
    pyqCount: 11,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Forouzan ch. 12-13",
    practice: "GATE Overflow Ethernet / CSMA tags",
    prereqs: "Data link layer",
  },
  {
    id: "cn-ip",
    subject: "Computer Networks",
    topic: "IPv4 addressing, subnetting, CIDR, supernetting, NAT, fragmentation",
    avgMarks: 1.7,
    trend: "Stable",
    pyqCount: 19,
    difficulty: "Easy",
    depth: "Medium",
    hours: 5,
    reference: "Forouzan ch. 19-20",
    practice: "GATE Overflow IP-Addressing / Subnetting tags (~110 Qs)",
    prereqs: "Number systems (binary)",
  },
  {
    id: "cn-routing",
    subject: "Computer Networks",
    topic: "Routing — distance vector, link state, RIP/OSPF/BGP basics, ICMP",
    avgMarks: 1.1,
    trend: "Stable",
    pyqCount: 13,
    difficulty: "Medium",
    depth: "Medium",
    hours: 4,
    reference: "Forouzan ch. 20-21",
    practice: "GATE Overflow Routing tag",
    prereqs: "IP addressing, shortest-path algorithms",
  },
  {
    id: "cn-transport",
    subject: "Computer Networks",
    topic: "Transport layer — UDP, TCP connection management, flow & congestion control",
    avgMarks: 2.0,
    trend: "Increasing",
    pyqCount: 22,
    difficulty: "Medium",
    depth: "High",
    hours: 7,
    reference: "Forouzan ch. 23-24 (Kurose & Ross ch. 3 for congestion control)",
    practice: "GATE Overflow TCP / Congestion-Control tags (~110 Qs)",
    prereqs: "Sliding window, IP addressing",
  },
  {
    id: "cn-app",
    subject: "Computer Networks",
    topic: "Application layer — DNS, HTTP, SMTP, DHCP, FTP",
    avgMarks: 0.8,
    trend: "Stable",
    pyqCount: 10,
    difficulty: "Easy",
    depth: "Low",
    hours: 3,
    reference: "Forouzan ch. 25-26",
    practice: "GATE Overflow Application-Layer-Protocols tag",
    prereqs: "Transport layer",
  },
  {
    id: "cn-sec",
    subject: "Computer Networks",
    topic: "Network security basics — symmetric/public key, digital signatures, TLS",
    avgMarks: 0.3,
    trend: "Decreasing",
    pyqCount: 5,
    difficulty: "Easy",
    depth: "Low",
    hours: 1,
    reference: "Forouzan ch. 31-32 (in-syllabus portions only)",
    practice: "GATE Overflow Network-Security tag (thin)",
    prereqs: "Application layer",
  },

  // ── Removed from syllabus ───────────────────────────────────────────
  {
    id: "rm-se",
    subject: "Removed from syllabus",
    topic: "Software Engineering — SDLC, testing, cohesion/coupling, cyclomatic complexity",
    avgMarks: 0,
    trend: "Decreasing",
    pyqCount: 7,
    difficulty: "Easy",
    depth: "Low",
    hours: 0,
    reference: "Pressman — not required",
    practice: "Do not practice. Zero questions since GATE 2021.",
    prereqs: "—",
    removed: true,
    note: "Dropped in the 2021 syllabus revision. Zero marks in GATE 2021-2025. Skip entirely.",
  },
  {
    id: "rm-web",
    subject: "Removed from syllabus",
    topic: "Web Technologies — HTML, XML, basic client-server",
    avgMarks: 0,
    trend: "Decreasing",
    pyqCount: 6,
    difficulty: "Easy",
    depth: "Low",
    hours: 0,
    reference: "Not required",
    practice: "Do not practice. Zero questions since GATE 2021.",
    prereqs: "—",
    removed: true,
    note: "Dropped in the 2021 syllabus revision. Skip entirely.",
  },
  {
    id: "rm-graphics",
    subject: "Removed from syllabus",
    topic: "Computer Graphics & Information Systems",
    avgMarks: 0,
    trend: "Decreasing",
    pyqCount: 3,
    difficulty: "Medium",
    depth: "Medium",
    hours: 0,
    reference: "Not required",
    practice: "Do not practice.",
    prereqs: "—",
    removed: true,
    note: "Not part of the post-2021 CS syllabus. Skip entirely.",
  },
]

export const SUBJECTS = Array.from(new Set(TOPICS.map((t) => t.subject)))

export interface Week {
  week: number
  month: number
  phase: Phase | "Revision" | "Mocks"
  title: string
  topicIds: string[]
  extras?: string[]
  checkpoint?: string
}

/**
 * 20-week plan at ~4.5 hrs/day ≈ 30 hrs/week ≈ 600 total hours.
 * Split roughly 65% theory+notes / 35% dedicated PYQ practice, with the
 * "50+ questions per chapter" rule folded into each week's allocation.
 */
export const ROADMAP: Week[] = [
  {
    week: 1,
    month: 1,
    phase: 1,
    title: "Discrete + Linear Algebra foundation",
    topicIds: ["dm-logic", "dm-sets", "em-matrices", "em-eigen"],
    extras: ["30 min/day General Aptitude quant from day one — never batch GA at the end"],
    checkpoint: "50+ Qs each on logic, sets/relations, eigenvalues",
  },
  {
    week: 2,
    month: 1,
    phase: 1,
    title: "Digital Logic end-to-end",
    topicIds: ["dl-number", "dl-boolean", "dl-comb", "dl-seq"],
    extras: ["Digital Logic is the cheapest full subject to finish — close it in one week"],
    checkpoint: "50+ Qs per DL chapter; full DL subject-wise PYQ set (2014-2025)",
  },
  {
    week: 3,
    month: 1,
    phase: 1,
    title: "C programming + linear data structures",
    topicIds: ["pds-c", "pds-recursion", "pds-linear"],
    extras: ["Trace every pointer/recursion question on paper — no compiler"],
    checkpoint: "50+ Qs on pointers, 50+ on recursion output-prediction",
  },
  {
    week: 4,
    month: 1,
    phase: 1,
    title: "Trees, heaps, hashing",
    topicIds: ["pds-trees", "pds-heap", "pds-hash", "pds-graphrep"],
    checkpoint: "MONTH 1 REVIEW — 1 sectional test on DL + PDS + Discrete (60 min)",
  },
  {
    week: 5,
    month: 2,
    phase: 1,
    title: "OS: scheduling, processes, synchronization",
    topicIds: ["os-process", "os-sched", "os-sync"],
    extras: ["Synchronization: hand-trace semaphore code, don't just read conclusions"],
    checkpoint: "50+ Qs each on scheduling and synchronization",
  },
  {
    week: 6,
    month: 2,
    phase: 1,
    title: "OS: memory management + deadlock",
    topicIds: ["os-mem", "os-vm", "os-deadlock", "os-file"],
    checkpoint: "Full OS subject-wise PYQ set; OS is now closed",
  },
  {
    week: 7,
    month: 2,
    phase: 1,
    title: "COA: cache + pipelining (highest marks-per-hour in the paper)",
    topicIds: ["coa-cache", "coa-pipeline", "coa-isa"],
    extras: ["Cache + pipelining alone average ~4.9 marks/yr — do every PYQ twice"],
    checkpoint: "50+ Qs cache, 50+ Qs pipelining",
  },
  {
    week: 8,
    month: 2,
    phase: 1,
    title: "Algorithms core: complexity, sorting, graph algorithms",
    topicIds: ["algo-asymp", "algo-sorting", "algo-graph", "algo-greedy"],
    checkpoint: "MONTH 2 REVIEW — sectional test on OS + COA + Algorithms",
  },
  {
    week: 9,
    month: 3,
    phase: 1,
    title: "Databases: SQL, normalization, transactions",
    topicIds: ["db-sql", "db-norm", "db-txn", "db-er"],
    checkpoint: "50+ Qs each on SQL, FD/normalization, serializability",
  },
  {
    week: 10,
    month: 3,
    phase: 1,
    title: "Networks: IP addressing, data link, transport",
    topicIds: ["cn-ip", "cn-dll", "cn-transport"],
    extras: ["Subnetting must become mechanical — target under 60s per question"],
    checkpoint: "50+ Qs subnetting, 50+ Qs sliding window + TCP",
  },
  {
    week: 11,
    month: 3,
    phase: 1,
    title: "Graph theory, probability, TOC entry",
    topicIds: ["dm-graph", "em-prob", "toc-fa"],
    checkpoint: "50+ Qs graph theory, 50+ Qs finite automata",
  },
  {
    week: 12,
    month: 3,
    phase: 2,
    title: "Phase 2 begins — TOC hard core",
    topicIds: ["toc-regex", "toc-cfg", "toc-tm"],
    extras: ["Phase 1 is now complete: ~78% of the paper's marks are covered"],
    checkpoint: "MONTH 3 REVIEW — first FULL-LENGTH mock (diagnostic, expect a low score)",
  },
  {
    week: 13,
    month: 4,
    phase: 2,
    title: "Dynamic programming + Compiler parsing",
    topicIds: ["algo-dp", "cd-parsing"],
    extras: ["The two hardest high-weightage topics in the paper — give them a full week"],
    checkpoint: "50+ DP table-fill Qs; build 10 LR/LALR tables by hand",
  },
  {
    week: 14,
    month: 4,
    phase: 2,
    title: "Combinatorics + remaining Compiler Design",
    topicIds: ["dm-comb", "cd-sdt", "cd-opt", "cd-icg", "cd-lex"],
    checkpoint: "Compiler Design closed; 50+ Qs combinatorics",
  },
  {
    week: 15,
    month: 4,
    phase: 3,
    title: "Phase 3 — cheap top-ups across subjects",
    topicIds: [
      "em-rv",
      "em-dist",
      "em-maxima",
      "em-limits",
      "em-integration",
      "em-stats",
      "dm-recurrence",
      "coa-io",
      "coa-memory",
    ],
    checkpoint: "Full-length mock #2 + error-log review",
  },
  {
    week: 16,
    month: 4,
    phase: 3,
    title: "Phase 3 continued + Phase 4 skim",
    topicIds: [
      "pds-balanced",
      "pds-scope",
      "db-ra",
      "db-index",
      "db-recovery",
      "cn-routing",
      "cn-mac",
      "cn-app",
      "cn-layers",
      "cn-sec",
      "os-syscall",
      "dl-impl",
      "coa-datapath",
      "dm-groups",
      "em-lu",
      "algo-dc",
    ],
    extras: ["Phase 4 skim only: NP-completeness reduction map, pumping lemma patterns"],
    checkpoint: "MONTH 4 REVIEW — full-length mock #3; syllabus is now 100% covered",
  },
  {
    week: 17,
    month: 5,
    phase: "Revision",
    title: "Revision cycle 1 — maths, DL, PDS, COA",
    topicIds: [],
    extras: [
      "Short notes only — no textbooks",
      "Re-solve every PYQ you got wrong in weeks 1-8",
      "2 full-length mocks this week (mocks #4, #5)",
    ],
    checkpoint: "Every wrong answer from months 1-2 re-solved correctly",
  },
  {
    week: 18,
    month: 5,
    phase: "Mocks",
    title: "Revision cycle 2 — OS, DBMS, CN, Algorithms",
    topicIds: [],
    extras: [
      "3 full-length mocks (#6-#8), one every alternate day, 9:30am slot to match exam timing",
      "Non-mock days: 4 hrs analysing the mock, not attempting new topics",
    ],
    checkpoint: "Mock score stabilising; accuracy above 80% on Phase 1 topics",
  },
  {
    week: 19,
    month: 5,
    phase: "Mocks",
    title: "Full-paper simulation week",
    topicIds: [],
    extras: [
      "4 full-length mocks (#9-#12) + 4 previous year papers under timed conditions",
      "Fix an attempt strategy: order of subjects, when to abandon a question, NAT vs MCQ risk",
    ],
    checkpoint: "Consistent attempt strategy; time per section locked in",
  },
  {
    week: 20,
    month: 5,
    phase: "Mocks",
    title: "Taper — formula sheets and light revision",
    topicIds: [],
    extras: [
      "2 light mocks early in the week, then stop",
      "Formula/standard-result sheets: cache, pipelining, TCP, FD closure, automata closure properties",
      "No new topics. Sleep on the exam schedule for the final 5 days.",
    ],
    checkpoint: "EXAM READY",
  },
]
